[package]
name = "mixini"
version = "0.1.0"
authors = ["Allen Bui <fairingrey@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
bincode = "1.3.3"
chrono = "0.4.19"
dotenv = "0.15.0"
lazy_static = "1.4.0"
lettre = { version = "0.10.0-rc.3", features = [
    "builder",
    "tokio1",
    "smtp-transport",
    "tokio1-native-tls",
], default-features = false }
libreauth = "0.14.1"
oso = { version = "0.21.0", features = ["derive"] }
rand = "0.8.4"
redis = { version = "0.21.2", features = ["aio", "tokio-comp", "connection-manager"], default-features = false }
regex = "1.5.4"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
sqlx = { version = "0.5.9", features = [
    "runtime-tokio-native-tls",
    "postgres",
    "uuid",
    "chrono",
    "json",
] }
surf = "2.3.1"
tantivy = "0.16.1"
tide = "0.16.0"
tokio = { version = "1.12.0", features = ["rt-multi-thread", "macros", "sync"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }
validator = { version = "0.14.0", features = ["derive"] }
