[package]
name = "mixini"
version = "0.1.0"
authors = ["Allen Bui <fairingrey@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
axum = "0.4.4"
bincode = "1.3.3"
chrono = "0.4.19"
dotenv = "0.15.0"
http = "0.2.6"
http-body = "0.4.4"
hyper = { version = "0.14.16", features = ["full"] }
lazy_static = "1.4.0"
libreauth = "0.14.1"
oso = { version = "0.25.1", features = ["derive", "uuid-07"] }
oxide-auth = "0.5.1"
oxide-auth-axum = "0.1.0"
rand = "0.8.4"
redis = { version = "0.21.5", features = [
    "aio",
    "tokio-comp",
    "connection-manager",
], default-features = false }
regex = "1.5.4"
serde = { version = "1.0.135", features = ["derive"] }
serde_json = "1.0.78"
sqlx = { version = "0.5.10", features = [
    "runtime-tokio-native-tls",
    "postgres",
    "uuid",
    "chrono",
    "json",
    "macros",
] }
tantivy = "0.16.1"
thiserror = "1.0.30"
tokio = { version = "1.15.0", features = ["rt-multi-thread", "macros", "sync"] }
tower = "0.4.11"
tower-http = { version = "0.2.1", features = ["add-extension", "trace"] }
tracing = "0.1.29"
tracing-subscriber = "0.3.6"
ulid = { version = "0.5.0", features = ["serde", "uuid"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }
validator = { version = "0.14.0", features = ["derive"] }

[dependencies.lettre]
version = "0.10.0-rc.4"
features = [
    "builder",
    "hostname",
    "tokio1",
    "smtp-transport",
    "tokio1-native-tls",
]
default-features = false
